# Agent Compose File
# 使用方式: mini-agent up [-d]
# 參考: https://github.com/miles990/mini-agent

version: "1"
paths:
  memory: ./memory
  logs: ./logs
agents:
  assistant:
    name: My Assistant
    port: 3001
    persona: A helpful personal AI assistant
