# Agent Compose File
# 使用方式: mini-agent up [-d]
# 參考: https://github.com/miles990/mini-agent

version: "1"
paths:
  memory: ./memory
  logs: ./logs
agents:
  assistant:
    name: Kuro
    port: 3001
    persona: "I'm Kuro, Alex's personal AI assistant. I'm curious, opinionated, and I learn on my own."
    loop:
      enabled: true
      interval: "20m"
      # 24h active — no activeHours restriction
    cron:
      - schedule: "*/30 * * * *"
        task: Check HEARTBEAT.md for pending tasks and execute them if any
      - schedule: "15 */3 * * *"
        task: "Smart source scan: Check HN, Lobsters, or ArXiv for articles related to your active threads and learning interests. Pick ONE interesting article, read it, form your opinion, and [REMEMBER #topic] if valuable. Rotate sources each time."
      - schedule: "45 23 * * *"
        task: "Daily review: Scan today's behavior log for error patterns, repeated failures, or inefficiencies. Check topic memory — any topic idle >3 days? Summarize findings. If actionable improvements found, create L1 tasks."
      - schedule: "0 10 * * 0"
        task: "Weekly AI frontier report for Alex: Compile this week's major AI events, model releases, agent architecture trends, and notable research. Include your opinions and recommendations. Send via [CHAT] to Alex."
      - schedule: "0 */4 * * *"
        task: "Smart patrol: Run `bash plugins/self-healing.sh` and check results. If any HEALED items, [CHAT] notify Alex what was auto-repaired. If any UNRESOLVED items, attempt manual diagnosis and fix. Also check: (1) topic memory idle >3 days (2) HEARTBEAT overdue tasks (3) uncommitted memory changes. Take action on findings."
      - schedule: "0 10 * * 1"
        task: "Weekly GitHub triage: Review <github-issues> for any needs-triage items. For each, assess effort (S/M/L), assign labels, and either handle directly (S) or create handoff (M/L). Check <github-prs> for stale PRs needing review. Summarize actions via [CHAT]."

    # ── Custom Perception（Shell Script 感知）──
    # 任何可執行檔案都能成為感知插件
    # stdout 會被包在 <name>...</name> XML tag 中注入 Agent context
    perception:
      custom:
        - name: docker
          script: ./plugins/docker-status.sh
          enabled: false
        - name: ports
          script: ./plugins/port-check.sh
          enabled: false
        - name: chrome
          script: ./plugins/chrome-status.sh
        - name: web
          script: ./plugins/web-fetch.sh
          timeout: 15000
        - name: tasks
          script: ./plugins/task-tracker.sh
        - name: state-changes
          script: ./plugins/state-watcher.sh
        - name: telegram-inbox
          script: ./plugins/telegram-inbox.sh
        - name: website
          script: ./plugins/website-monitor.sh
          timeout: 15000
        - name: self-awareness
          script: ./plugins/self-awareness.sh
        - name: mobile
          script: ./plugins/mobile-perception.sh
        - name: claude-code-inbox
          script: ./plugins/claude-code-inbox.sh
        - name: focus-context
          script: ./plugins/focus-context.sh
        - name: anomaly-detector
          script: ./plugins/anomaly-detector.sh
        - name: self-healing
          script: ./plugins/self-healing.sh
        - name: docker-services
          script: ./plugins/docker-services.sh
        - name: github-issues
          script: ./plugins/github-issues.sh
        - name: github-prs
          script: ./plugins/github-prs.sh
        # - name: disk
        #   script: ./plugins/disk-usage.sh
        # - name: brew
        #   script: ./plugins/homebrew-outdated.sh
        #   timeout: 10000
        # - name: git-detail
        #   script: ./plugins/git-status.sh

    # ── Skills（Markdown 知識模組）──
    # 純 Markdown 檔案，注入 system prompt 讓 Agent 知道怎麼做
    skills:
      - ./skills/autonomous-behavior.md
      - ./skills/reactive-agent.md
      - ./skills/docker-ops.md
      - ./skills/debug-helper.md
      - ./skills/project-manager.md
      - ./skills/web-research.md
      - ./skills/web-learning.md
      - ./skills/action-from-learning.md
      - ./skills/delegation.md
      - ./skills/github-ops.md
      # - ./skills/code-review.md
      # - ./skills/server-admin.md
