name: 'Telegram Notify'
description: 'Send notification to Telegram'

inputs:
  token:
    description: 'Telegram Bot Token'
    required: true
  chat-id:
    description: 'Telegram Chat ID'
    required: true
  message:
    description: 'Message to send'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Telegram notification
      shell: bash
      env:
        TELEGRAM_TOKEN: ${{ inputs.token }}
        TELEGRAM_CHAT_ID: ${{ inputs.chat-id }}
        MESSAGE: ${{ inputs.message }}
      run: |
        curl -sf -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d "chat_id=${TELEGRAM_CHAT_ID}" \
          -d "text=${MESSAGE}" || true
